### ISSUE TITLE
Getting post error when uploading large image > 2G.

### ISSUE THREAD

**Issue by manish-nuance** [singularityhub/sregistry#139] opened 2018-08-28 15:42 UTC
Hi,

I'm trying to upload an image >2G in size via Web UI. It's being "The connection was reset." issue.
Seeing at logs it states:
nginx_1   | ****** - - [28/Aug/2018:15:34:19 +0000] "POST /upload HTTP/1.1" 400 0 "https://xyz/api/upload/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
nginx_1   | ******* - - [28/Aug/2018:15:38:33 +0000] "POST /upload HTTP/1.1" 400 0 "https://xyz/api/upload/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"

Can you provide any help on this?

**Comment by vsoch** [comment] 2018-08-28 15:56
Hey! A few questions:
 - does it work with smaller images
 - have you tried the command line upload (for small and large).

400 is a permissions error, so I think maybe look into the user you are using, what permissions he/she has across the registry (and for the collection).

**Comment by manish-nuance** [comment] 2018-08-28 16:07
It's working with smaller images and using same user for upload image.
Not tried with command line upload yet.
I guess, Permission issue would not be case, while smaller image (<=2G) are being uploaded.

**Comment by vsoch** [comment] 2018-08-28 16:19
It might be a limit set by the browser? I don't really know how to debug without looking at it, browsers are hard like that. I am also not terribly experienced with Windows. Try command line and see what you get.

**Comment by manish-nuance** [comment] 2018-08-29 16:56
Hi vsoch,

Today, I tried to upload larger image (appx 2.4gb) with command line. but it immediately terminates the uploads with following error..

[1. Collection return status 200 OK]
('Connection aborted.', OSError("(104, 'ECONNRESET')",))

**Comment by vsoch** [comment] 2018-08-29 19:16
I think it's related to not doing a retry when it should on POST, see this long issue --> https://github.com/requests/requests/issues/3845 

The only way to debug is to interactively step through the client and get the full error and traceback, and this is something I'm not able to help with. If you are able to walk through the client's code:

1. You would start by creating a client as is done here:
https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/client/push.py#L28

2. But instead of just calling push, then go to the function and walk through the steps for push:
https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/registry/push.py#L45

3. The step that is working to get the collection, this message:

```
[1. Collection return status 200 OK]
```
is represented in this section:
https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/registry/push.py#L60

and the part you would want to debug / get traceback (and inspect headers and raw body for) is the following section:
https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/registry/push.py#L86

Based on seeing a tuple with a message an error, that's telling us that it's hitting here in the try,catch
https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/registry/push.py#L117

and it's those returned objects we want to see everything about and debug further.

Good luck! I'd be glad to help if you want to go through that, please post details of the commands you are doing and outputs, and any questions you have.

**Comment by victorsndvg** [comment] 2018-10-01 08:35
Hi again,

I was able to print `traceback.print_exc(file=sys.stdout)` in the generic exception catch block in this line:

https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/registry/push.py#L117

This is the output:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1055, in _send_output
    self.send(chunk)
  File "/usr/local/lib/python3.7/http/client.py", line 977, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.7/ssl.py", line 1012, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.7/ssl.py", line 981, in send
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1055, in _send_output
    self.send(chunk)
  File "/usr/local/lib/python3.7/http/client.py", line 977, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.7/ssl.py", line 1012, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.7/ssl.py", line 981, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/sregistry-cli/sregistry/main/registry/push.py", line 116, in push
    r = requests.post(url, data=monitor, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
Any suggestion?

**Comment by vsoch** [comment] 2018-10-01 11:08
What I would try next is to extract the call from the client so you can perform it with curl. You can do this by putting a bunch of print statements in the push.py so that you see all the calls that go to requests. I don't actually see any new information from what you shared about - it's still 104 / Connection reset by peer. A few possible reasons this happens to look into:

 - [issue with openssl](https://github.com/requests/requests/issues/2543)
 - [content header specified is smaller than actual](https://github.com/fdintino/nginx-upload-module/issues/13)

Since the endpoint works for smaller images (yes?) it would be useful to try and test it outside of the python module first, and look at the exact headers, etc. that go back and forth when it works and how that differs when it doesn't. This is what I usually do to test.

**Comment by victorsndvg** [comment] 2018-10-01 11:35
HI @vsoch ,

can you point out how you exactly get the curl call info from push.py?

I mean, what I need to print and how I build the curl call then.

Thanks in advance!

**Comment by vsoch** [comment] 2018-10-01 11:44
Yes you need all the python variables starting with URL here https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/registry/push.py#L86 and then to look at the requests objects that are created and returned, especially headers. I don't know in advance how to build the call, I'd just google search to figure it out based on what I see those objects looking like.

**Comment by victorsndvg** [comment] 2018-10-01 11:45
I can add some more debugging information. May it can be useful for you.

print(encoder):
```
<MultipartEncoder: {'SREGISTRY_EVENT': 'SREGISTRY-HMAC-SHA256 Credential=upload/dnNhbmRl/20181001T11Z,Signature=b2c4a039ab3b0e29fe68c69696f2d0e8a229d824ef63e44b7894c90309813ada', 'name': 'test', 'collection': '1', 'tag': 'test', 'file1': ('test:test.simg', <_io.BufferedReader name='/mnt/lustre/scratch/home/cesga/vsande/mso4sc-feelpp-toolboxes:develop-v0.105.0-alpha.2-ubuntu-16.04.simg'>, 'text/plain')}>
```

print(dump.dump_all(r)):
```
bytearray(b'< POST /api/upload/chunked_upload HTTP/1.1\r\n< Host: sregistry.srv.cesga.es\r\n< User-Agent: python-requests/2.19.1\r\n< Accept-Encoding: gzip, deflate\r\n< Accept: */*\r\n< Connection: keep-alive\r\n< Authorization: SREGISTRY-HMAC-SHA256 Credential=push/dnNhbmRl/20181001T11Z,Signature=844b60b5b93319d1966d3882af4b7cde04d0a1af9b1c1a465d58828d4ebb9a38\r\n< Content-Length: 55\r\n< Content-Type: application/json\r\n< \r\n< {"collection": "mso4sc", "name": "test", "tag": "test"}\r\n> HTTP/1.1 200 OK\r\n> Server: nginx\r\n> Date: Mon, 01 Oct 2018 11:42:07 GMT\r\n> Content-Type: application/json\r\n> Content-Length: 10\r\n> Connection: keep-alive\r\n> X-Frame-Options: SAMEORIGIN\r\n> \r\n{"cid": 1}')
```

**Comment by vsoch** [comment] 2018-10-01 11:46
yes those are the objects you need to inspect. A print just shows what they have in the __str__() function I can't magically look at them and tell you anything :)

**Comment by vsoch** [comment] 2018-10-01 11:46
You need to interactively debug them, likely with ipython, so you can more closely inspect the objects. That's all I can offer for advice.

**Comment by vsoch** [comment] 2018-10-01 11:47
> Thanks @vsoch , I'm already trying, but without success yet...
This is pretty much a summary of my entire existence, for just about everything :) Welcome to being a developer.

**Comment by victorsndvg** [comment] 2018-10-01 12:00
hahah I am a develop since several years ago, but nothing related with web things. I'm used to the (hard) test/error process ... 

Anyway, any clue you can give me is welcome :)

**Comment by vsoch** [comment] 2018-10-01 12:15
Haha, well I'm a pretty terrible developer - the only insight I have for most things is that I approach it knowing that I know almost nothing, reduce the problem to its simplest components, then look really carefully at them and try many iterations of similar things until some insight reveals itself. And I definitely agree - web stuff is harder because there are so many layers of permissions, servers, containers... the best thing is just to not give up or get frustrated in most cases. if you do get frustrated, just take a break from it and work on something else for a while.

**Comment by victorsndvg** [comment] 2018-10-01 12:38
Wow, curlify is my best friend today!  ( https://github.com/ofw/curlify )

The problem is that I don't know how to replace `-d '<requests_toolbelt.multipart.encoder.MultipartEncoderMonitor object at 0x7f71511eb630>'` into something with sense outside python ... Do you?

**Comment by vsoch** [comment] 2018-10-01 12:43
That object is just mimicking a multi part encoded form post, so I’d inspect its headers when it’s working and go from there. There are lots of good examples https://markhneedham.com/blog/2013/09/23/curl-postupload-multi-part-form/. Try to reproduce a working call first and then the error.

**Comment by victorsndvg** [comment] 2018-10-01 15:16
Uff no idea... I can't spend to much time in it right now ... I don't know how to provide you useful information to go deep into the issue

**Comment by victorsndvg** [comment] 2018-10-03 15:35
@vsoch ,

no idea about the origin of the issue. I went back to the past and try old things like this:
https://github.com/singularityhub/sregistry/issues/108#issuecomment-372728478

If I use the http protocol instead of https to upload the file it works.

I tried with redirections from the nginx conf file. I mean, redirect every http call to https except `/upload` and redirect https call to `/upload` to http. This doesn't work.

Is there any workaround to:
 - Use always http protocol for files upload?
or
 - Provide the token with http protocol by default (even serving everything in https)?
or
 - Any other better solution that I cannot figure out because of my basic web knowledge ...?

Thanks for your help!

**Comment by vsoch** [comment] 2018-10-03 15:53
If it works for http, it's probably an issue with your nginx configuration to direct there. You also might want to check your domain name under [config.py](https://github.com/singularityhub/sregistry/blob/master/shub/settings/config.py).

**Comment by victorsndvg** [comment] 2018-10-04 08:34
Hi @vsoch ,

I checked my config.py, it's based on the one you are providing. My domain name is `https://sregistry....`.

taking as starting point:
  - My sregistry server is hosted and served under HTTPS (by default)
  - HTTPS downloads are working perfectly
  - HTTPS uploads are not working for big images
  - I need a (somehow) "bullet-proof" container registry
  - We are delivering our own containerized `sregistry-cli`

I did a workaround, maybe not desirable for everybody, but at least work for me. Here I share the workaround:

I changed the following line in `sregistry` server:
https://github.com/singularityhub/sregistry/blob/master/shub/apps/api/templates/routes/upload.html#L12
by this one:
```
    <form name="upload" method="POST" enctype="multipart/form-data" action="http://{{ request.META.HTTP_HOST }}/upload">
```

I changed the following line in `sregistry` client:
https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/registry/push.py#L86
by this one:
```
    url = '%s/upload' % self.base.replate('https://','http://').replace('/api','')
```

What do you think?
Maybe others can be interested in it?

**Comment by vsoch** [comment] 2018-10-04 11:47
I don’t think disabling https is the right way to go. See this issue https://github.com/fdintino/nginx-upload-module/issues/87 maybe something you could try in there?

**Comment by sysmso** [comment] 2018-11-29 09:51
Same problem here with sregistry client. I'm interested of someone found a workaround or a fix... 
When submitting images > 2G we have a Broken PipeError :
`[1. Collection return status 200 OK]
('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
`

**Comment by RonaldEnsing** [comment] 2019-09-04 11:11
> Hi @vsoch ,
> 
> I'm obtaining the same issue with bit images. It works with 1Gb, 2Gb images, but fails with 4Gb images.
> 
> I'm ready to debug it! what info do you need to track the error?
> 
> this is what I get right now:
> 
> ```
> ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> ```

Could it be related to the file system that you have on the server? For example, the maximum supported file size is slightly smaller than 4 GB on a FAT32 file system.

**Comment by vsoch** [comment] 2019-09-04 11:58
Try increasing the max body size https://www.tecmint.com/limit-file-upload-size-in-nginx/ or building smaller images.

**Comment by vsoch** [comment] 2019-09-04 12:47
Also take a look at the buffer size in `uwsgi.ini`, e.g.,:

```
buffer-size=65535
```
But generally, those images are huge! You should consider optimizing them too :)

**Comment by RonaldEnsing** [comment] 2019-10-08 11:35
> Same problem here with sregistry client. I'm interested of someone found a workaround or a fix...
> When submitting images > 2G we have a Broken PipeError :
> `[1. Collection return status 200 OK] ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')) `

I am running into something similar, but only after I changed from http to https:
```
[1. Collection return status 200 OK]
Traceback (most recent call last): 0/2581 MB - 00:00:00
...
OpenSSL.SSL.SysCallError: (32, 'EPIPE')
```
I did not have any issues before with http. Any thoughts?

> But generally, those images are huge! You should consider optimizing them too :)

I agree that images should be as small as possible. The image should not contain anything that is unused. However, images can easily be larger than 2 GB. A maximum of 2 GB is a serious limitation. Docker images are often larger as well. I think that a 2GB docker image is not considered large. Why would a 2 GB singularity image be considered large? Any idea how this works with the docker registry, which supports much larger file sizes? Maybe the singularity registry can benefit from how this is solved in the Docker registry.

**Comment by vsoch** [comment] 2019-10-08 12:19
Did you try changing the buffer size? I’ll all ears for things to try - I’m not sure what we should try, specifically.

**Comment by vsoch** [comment] 2019-10-08 12:23
There are some ideas here! It could be Python related, or we could add a missing header. https://github.com/sigmavirus24/github3.py/issues/779 Thoughts?

**Comment by vsoch** [comment] 2019-10-08 13:01
Another idea that I think I think is to add the Sylabs library push endpoint, so you can push with Singularity. There is no documentation for it, so it would primarily be about triggering errors and looking at the source code to figure out the logic. I don't use Sylabs cloud so if someone wanted to try to get started, we could pursue this! For most endpoints it comes down to adding `--library` or `--url` as arguments.

**Comment by RonaldEnsing** [comment] 2019-10-08 13:32
> Did you try changing the buffer size? I’ll all ears for things to try - I’m not sure what we should try, specifically.

I tried that as well. I am getting a `OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')`. Still, I am having issues only with large images (e.g. 2,4GB) and no issues with smaller images (e.g. 900MB).

**Comment by vsoch** [comment] 2019-10-08 13:50
@RonaldEnsing please see my post above. I'd like to deduce if this is just a Python thing, and if so, we could develop another way to push. Most ideally I'd like to engineer the Sylabs library endpoint - so if you have some bandwidth to start messing with that (and share what you learn) I will catch up when I can make some time! I definitely agree we need a solution here, and I'm willing to put in whatever effort it takes.

**Comment by RonaldEnsing** [comment] 2019-10-08 14:06
> @RonaldEnsing please see my post above. I'd like to deduce if this is just a Python thing, and if so, we could develop another way to push. Most ideally I'd like to engineer the Sylabs library endpoint - so if you have some bandwidth to start messing with that (and share what you learn) I will catch up when I can make some time! I definitely agree we need a solution here, and I'm willing to put in whatever effort it takes.

I will let you know when I know more. I will need to find out which (curl) command to use in order to find out if it is python related. Any suggestions are welcome of course. By the way, I tried to upload these images using the web interface as well. With the image of >2GB I get a 'Secure Connection Failed': `PR_CONNECT_RESET_ERROR` in firefox. With the small image, the upload works fine.

**Comment by vsoch** [comment] 2019-10-08 14:08
And I'll take a look as soon as I am able - there is some big conference for the lab I develop for and every day is an inundation of new (large) feature requests so it likely won't be this week! But it's on my list and I _will_ make time for it.

**Comment by vsoch** [comment] 2019-10-09 21:42
hey everyone I'm making good progress with engineering the library push endpoint - actually the first bits that needed to be done were server and client functions to verify a token, here's how that looks so far:

---------------------------------------------------

## Singularity Push

As of version `1.1.10`, Singularity Registry Server offers a library endpoint
to authenticate and then push containers. First, create an endpoint for your
registry:

```bash
$ singularity remote add --no-login DinosaurCloud cloud.dinosaur.io
```

Verify it's there:

```bash
$ singularity remote list
NAME           URI              	GLOBAL
DinosaurCloud  cloud.dinosaur.io        NO
[SylabsCloud]  cloud.sylabs.io   	YES
```

**Important** Sylabs requires these endpoints to have https, for obvious reasons.
If you want to test with localhost, you'll need to edit [this file](https://github.com/sylabs/singularity/blob/5e483be4af2e120e646d33f0757e855c8d3be2da/internal/pkg/remote/remote.go#L237)
and re-compile Singularity to set the url to have http. That's how
I developed this set of endpoints.

Then you'll first need to get your token at the /token endpoint, for example:

```bash
TOKEN=1eb5bc1daeca0f5a215ec242c9690209ca0b3d71
```

And then provide it to the Singularity client to create a remote endpoint for your registry:

```bash
$ singularity remote login DinosaurCloud
INFO:    Authenticating with remote: DinosaurCloud
Generate an API Key at https://127.0.0.1/auth/tokens, and paste here:
API Key: 
INFO:    API Key Verified!
```

If you paste a token that isn't valid, you'll get a different message

```bash
$ singularity remote login DinosaurCloud
INFO:    Authenticating with remote: DinosaurCloud
Generate an API Key at https://127.0.0.1/auth/tokens, and paste here:
API Key: 
FATAL:   while verifying token: error response from server: Invalid Token
```

I don't get a lot of time to work on this each day, but if I keep it up we'll make progress! I'll update here as I do more.

**Comment by vsoch** [comment] 2019-10-12 15:39
omg I fixed it, and everything working! Will push changes and point you to how to test asap.

**Comment by vsoch** [comment] 2019-10-12 15:57
here you go! https://github.com/singularityhub/sregistry/pull/240 I would suggest testing locally, which does mean a bit of work to build the containers, ensure you have secrets to login, and you'll also need to compile a custom singularity to change one https hard coded string to http to allow for your localhost to be remote.

**Comment by vsoch** [comment] 2019-10-16 19:41
hey folks - will anyone get a chance to test? https://github.com/singularityhub/sregistry/pull/240

**Comment by RonaldEnsing** [comment] 2019-10-17 08:00
Thank you @vsoch. I will definitely need these changes. This is perfect. However, I will not be able to test this in the coming days. I will let you know once I tested this. It may take some time before I get to this.

**Comment by vsoch** [comment] 2019-10-17 14:28
Great, thank you for letting me know!

**Comment by vsoch** [comment] 2019-10-27 16:54
okay @kamedodji  has tested! He learned that you need Singularity 3.3.0 or later for the library endpoint. @RonaldEnsing still no rush  on your part, but (making a mental and written note here) once you test we will be good to merge.

**Comment by RonaldEnsing** [comment] 2019-11-07 10:57
I am running into `sregistry_nginx_1 exited with code 1` after `unknown directive "upload_max_filesize" in /etc/nginx/nginx.conf:17` when doing `docker compose up`. If I comment this setting, then I am only able to upload smaller images. Any ideas what would cause this?

**Comment by vsoch** [comment] 2019-11-07 12:19
Can you double check the Nginx image you are using? Try stopping and removing all containers, pulling it again, and bringing it up.

**Comment by vsoch** [comment] 2019-11-07 13:08
Actually @RonaldEnsing I'm thinking this through again - the updated nginx container can't be on quay yet (the PR isn't pushed!) so I think if I remember correctly, what I did is to build it locally. So you'd still want to stop and remove containers, but then cd into nginx:

```bash
docker build -t quay.io/vanessa/sregistry_nginx .
```
Then when you bring it up it should re-create that with the updated container.

**Comment by RonaldEnsing** [comment] 2019-11-07 13:56
This is what I did:

```
docker system prune -a
git clone -b test/library-auth-push https://www.github.com/singularityhub/sregistry sregistry
cd sregistry
docker build -t quay.io/vanessa/sregistry .
cd nginx
docker build -t quay.io/vanessa/sregistry_nginx .
cd ..
docker-compose up
```

This results in the `unknown directive "upload_max_filesize" in /etc/nginx/nginx.conf:17` as I've written above.

**Comment by vsoch** [comment] 2019-11-07 14:06
Okay I'm going to rebuild all my containers and see if I can reproduce.

**Comment by vsoch** [comment] 2019-11-07 14:36
okay we just needed to remove those two directives - I'm not sure why I didn't (it looks like I was testing and then updated the live running container to remove them and forgot to update the description in the README). What I've just done is removed them, rebuilt the containers, and then tried pushing the same 8GB container. First I got a read timeout (504)

```bash
WARNING: Skipping container verifying
INFO:    http://127.0.0.1
INFO:    ff4a371320ad839e54cd2cc27a4ce861688f8e7a
INFO:    library://vsoch/dinosaur-collection/rustarok
INFO:    []
 8.09 GiB / 8.09 GiB [================================================================] 100.00% 71.90 MiB/s 1m55s
FATAL:   Unable to push image to library: error uploading image: HTTP status 504
```
but the second time it worked

```bash
$ singularity push -U /home/vanessa/Documents/Dropbox/Code/rust/rustarok/rustarok_latest.sif library://vsoch/dinosaur-collection/rustarok:latest
WARNING: Skipping container verifying
INFO:    http://127.0.0.1
INFO:    ff4a371320ad839e54cd2cc27a4ce861688f8e7a
INFO:    library://vsoch/dinosaur-collection/rustarok:latest
INFO:    [latest]
 8.09 GiB / 8.09 GiB [================================================================] 100.00% 97.12 MiB/s 1m25s
```
It looks like we might be able to set `uwsgi_read_timeout` if this error happens for you - https://stackoverflow.com/questions/35810749/nginx-504-gateway-timeout-error-for-django I just pushed changes so you should be able to pull and rebuild.

**Comment by vsoch** [comment] 2019-11-07 15:22
Awesome! Apologies for the hiccup.

**Comment by vsoch** [comment] 2019-11-07 15:22
Let me know when you are happy and it's ready to merge.

**Comment by RonaldEnsing** [comment] 2019-11-07 15:42
I think this is ready to merge.

**Comment by vsoch** [comment] 2019-11-07 17:12
I think we can now close this, as the PR is merged! I want to say thank you to everyone for helping out, and for your patience! This was a hard one.

**Closed by vsoch** 2019-11-07 17:12 UTC
