### ISSUE TITLE
Support for several tags per image

### ISSUE THREAD

**Issue by prudhomm** [singularityhub/sregistry#163] opened 2018-10-13 10:15 UTC
Docker allows for tagging an image with several tags. 
is that doable with singularity/sregistry?
sregistry could play an important role here because it would be the tag handler

for example
```
sregistry tag mso4sc/feelpp-toolbox:develop-v0.106.0-ubuntu-16.04 mso4sc/feelpp-toolbox:v106
sregistry tag mso4sc/feelpp-toolbox:develop-v0.106.0-ubuntu-16.04 mso4sc/feelpp-toolbox:latest

sregistry tag mso4sc/feelpp-toolbox:develop-v0.105.0-ubuntu-16.04 mso4sc/feelpp-toolbox:v105 
sregistry tag mso4sc/feelpp-toolbox:develop-v0.105.0-ubuntu-16.04 mso4sc/feelpp-toolbox:production
```
Encoding the tag in the filename when a pull is done is then a bad idea. A docker-like system would be better and an image is identified uniquely with a uuid.

/cc @trophime @victorsndvg

**Comment by vsoch** [comment] 2018-10-13 12:57
The sregistry command (as you've shown) would manage your local database, is this what you intend? 

> Encoding the tag in the filename when a pull is done is then a bad idea.

Why? it's the easiest way to distinguish images. If you want a truly unique ID you should not use the tag, you should use the hash of the container.

**Comment by vsoch** [comment] 2018-10-13 13:02
My thinking is that encoding the tag in a location anywhere other than where the image is built from (e.g., Github /version control) or away from the image itself (hence the file name) isn't a great idea. What I do think makes sense is pulling based on a unique id (hash of the file), or based on a tag that is represented within the image (either the hash or a recipe under version control that specifies the same tag). I think an arbitrary tag in either the local sregistry database or the server doesn't go as far. I'm definitely interested to help meet your needs here, could you give me a sense of the overall goal, and suggestions for implementation?

**Comment by prudhomm** [comment] 2018-10-14 05:04
@vsoch I probably misunderstand something about sregistry/singularity. I am a bit more familiar with docker. What I would like to do is have several tags per singularity image without duplicating the image locally.
If I look at https://sregistry.srv.cesga.es/collections/1 where we have a few of our containers only one tag is possible per image. Am I correct or have I misunderstood something?
My use case is the following: I have containers with fixed tags corresponding to _e.g._ releases of our software possibly encoding information like branch version and system (_e.g_ `develop-v0.106.0-ubuntu-16.04` or `v106` or `develop`). Then I have moving tags( _e.g._ `stable` `latest` `production` `development`) that are updated by the development/deployment process.
Now I understand that pulling a container allows you to get access directly to the image and the end-user needs to identify it which is why the tag is encoded in the filename.
A related question is : if I push a singularity image, the same, with two different tags, is it duplicated or only one copy is stored in sregistry (_e.g._ at CESGA)?
Pulling locally currently would duplicate the two images.

I hope I am making sense.

**Comment by vsoch** [comment] 2018-10-15 11:59
@victorsndvg I could maybe see adding a "tag" option to sregistry-cli to minimally help with push, but why not just do:

```
export SREGISTRY_CLIENT=registry
CONTAINER=$(sregistry get collection/image:previous-tag)
sregistry push --name collection/image:updated-tag $CONTAINER
```

**Comment by victorsndvg** [comment] 2018-10-15 12:44
@vsoch, I'm not focusing on what happens with the local registry right now, but on the server side.

I think a common workflow while delivering software (mostly in Dockerhub, but also in Git repos, etc.) is  to tag the latest stable software version with `latest`/`stable`/`or-whatever-tag` but also maintaining the original tag `v106` with the release id.

For a user (who is not following the development cycle of a particular software) is useful to obtain directly to the most up-to-date version (the one with the `latest` tag) without knowing too much details about the release name, tag or whatever.

Based on this user behavior, the developer (or software provided) could be interested in provide both tags, one with the release id and one with the `latest` tag pointing to the same image. 

As you said, this can be done by pushing the same image twice with different name/tags. The problem with this approach is that you are duplicating the container on the server side. With small registries this is not a big problem, but what if the registry scale? I think it has no sense to have hundreds/thousands of MB/GB/TB of duplicated files. This is what we are trying to avoid.

It has more sense for you?

**Comment by vsoch** [comment] 2018-10-15 16:08
It makes sense, but adding another level of abstraction is not something I am eager to do. Especially because:

 -  you can accomplish what you need without it
 - it encourages you to think harder about what images you do push / provide with different tags (twice)
 - the implementation to need to check previous tags and then decide on some "default actions" given an existing tag is removed, or over-ridden, is going to complicate things beyond the simplicity that I want the registry to have.

There are other things that are priority to this issue I think. Feel free to come up with some elegant solution and PR for review, but it is not something I will jump on.

**Comment by vsoch** [comment] 2018-10-15 16:28
I would go further and say that having the `latest` tag as some standard, just based on Docker, has been terrible practice for reproducibility. The "latest" that you get today is not the latest tomorrow, and it is worse to get something that is different (than not know it) than get a previous version. I think being explicit to specify the container you need is far better practice than adding these abstractions of "latest" "stable" etc. So I would challenge you to find some middle ground - either a strategy you have locally to define the version that is latest, or a different implementation that does not add an abstraction, and does not chance this issue that the container a user asks for today has changed (but has the "same tag").

**Comment by victorsndvg** [comment] 2018-10-16 06:44
@vsoch , I agree with you. This is not mandatory for us and we don't need to rush to find a solution. We don't have too much time (and the expertise) to implement it, but we can discuss the problem. Maybe the solution we are proposing is not the best one, but I think is something we can think about for managing risks, providing more flexibility and avoiding possible future problems.

I think, the reproducibility issue is still there since we can overwrite a particular `collection/container:tag` in the server side. Only if we `frozen` it (and we do change it), from the server side and before downloading the image, we can ensure  that the image is always the same. I think trying to enable reproducibility based on a naming convention is prone to errors.

The hash is the property that ensures an image is the same than other. If we can assign new tags per image and we can frozen a tag, we can get the same model as the current one but with an extra level of flexibility. 

Why not to use the hash for reproducibility and the tag as a naming convention? 

Why not to provide a feature to the client to download a particular hash without the need of being aware of a particular naming convention as a mechanism for reproducibility?

These are only thoughts, I don't want to bother you.

What do you think?

**Comment by vsoch** [comment] 2018-10-16 09:27
> I think, the reproducibility issue is still there since we can overwrite a particular collection/container:tag in the server side. Only if we frozen it (and we do change it), from the server side and before downloading the image, we can ensure that the image is always the same. I think trying to enable reproducibility based on a naming convention is prone to errors.

Agree - it's still there. The subtle difference is that in one case the tool is supporting a particular practice (e.g., having tags is making it easy to have a "latest" image that changes) vs. the latter is that it's a choice made by the user. 

> The hash is the property that ensures an image is the same than other. If we can assign new tags per image and we can frozen a tag, we can get the same model as the current one but with an extra level of flexibility.

This is also true! But in practice (or at least my observation / experience) it's a rare case that a user goes as far as to ask for a particular hash.

> Why not to use the hash for reproducibility and the tag as a naming convention?

For the reasons stated above - a user would typically treat a tag as we would want them to treat a hash. Actually, the times I've been most reproducible (in specifying even a particular tag) is when the "latest" tag isn't available, my build/pull fails, and I'm forced to look it up. I still don't grab a hash, though, I grab a tag. Hashes seem to be mostly used for download verification.

> Why not to provide a feature to the client to download a particular hash without the need of being aware of a particular naming convention as a mechanism for reproducibility?

Could you give an example of what you mean here? At least now with Singularity (and this is something I implemented waaay back) you can add --commit or --hash to download the image named by either of those things.

**Comment by vsoch** [comment] 2019-05-08 15:15
Singularity Registry server keeps an image hash, so it would be reasonable to have the client first do a query for an existing container. In the case that it's in a different collection (meaning different ownership) I would say the upload should still happen. In the case that it's the user's collection (and the container already exists with the same name /tag) this could be skipped over. Would this fit your needs?

**Comment by Flamefire** [comment] 2019-05-09 07:34
> Singularity Registry server keeps an image hash

The image hash is something like `sha256.792d54235dcfd46e6fb9b1501f4ccf4d4d18b3d7d69199e5be2547d85c6d98e9` I think I've seen it on sregistry too. 

> so it would be reasonable to have the client first do a query for an existing container.

Does sregistry already provide a query based on this hash?

> In the case that it's in a different collection (meaning different ownership) I would say the upload should still happen.

Seems consistent with the Library implementation (see above: Only 1 collection mentioned per image)

> and the container already exists with the same name /tag

It **must** be same hash, not same name/tag. At the least I'd mirror behaviour of the Library: Store one file per `entity/collection/name` (tuple not OR) but not duplicate the file for different tags (use case see above: image x has tags `v1.1` and `latest`)

The previously described behaviour (store image once per *hash* even if different collection) would be space optimal which may be a huge win as images can get quite large and (fast) storage is expensive.

Well, I'd suggest to start with the "tag deduplication". This could be done entirely on the server (for later extension) and when implementing the library:// protocol #190 the upload skipping comes for free.

**Comment by vsoch** [comment] 2019-05-09 14:43
A few quick answers:
 - The hash on sregistry (I believe) is either sha256 or md5, I'd have to check.
 - There is no query based on a hash, so I would need to add this endpoint. The push client for sregistry-cli would need to be modified to not push if it finds the image already exists in the collection.
 - I'm not comfortable having different collections (with different users, permissions) share the same binary file. What happens if someone deletes it? It comes down to giving one binary double ownership, and if I were a container owner I wouldn't want that. This is a design decision, yes.

To be clear, I don't have compelling enough reason to try and reverse engineer the library endpoint. You've said that you aren't even sure about running it given docker, and as I've shared above, Sylabs is planning to have a hosted model. If/when you decide that you would use it, I'd be happy to add an endpoint to check for existence in a collection based on a hash, and then an update to sregistry-cli to use it.

**Comment by Flamefire** [comment] 2019-05-09 15:20
This is independent of the library protocol, just wanted to mention that upload skipping there is already implemented. Upload skipping is optional for the matter of this, only skipping to store it needs to be implemented

That's why I have given options and comparison with the SCS implementation as far as it is deducable from the API. Not saying you need to implement another protocol, just take inspiration how others are doing it (having multiple tags per image and avoiding duplicating files)

>  It comes down to giving one binary double ownership, and if I were a container owner I wouldn't want that.

This is not the choice of a "container owner" but rather an implementation detail of the registry. It is purely an optimization (see [FlyWeight pattern](https://en.wikipedia.org/wiki/Flyweight_pattern)): You have a large chunk of data and instead of storing the same chunk of data multiple times you store it once and keep references to it. When the last reference is deleted you delete the data.

As far as I can tell you already have the means to implement this:
- https://github.com/singularityhub/sregistry/blob/8bd6e1619fb54700fbf59ae5c8f403782c9c2c86/shub/apps/main/models.py#L303 A `Container` references an `ImageFile`
- Instead of creating a new `ImageFile` https://github.com/singularityhub/sregistry/blob/3fe0021c69c5a465dbcb870f3059103a24882928/shub/apps/api/actions/create.py#L130 you could look it up by hash and reuse that
  - Possibly limit the scope here if you want that
  - I don't see why e.g. `tag` needs to be duplicated in `Container` and `ImageFile`
- TODO: (not) deleting

>  If/when you decide that you would use it

Just want to provide additional input for use by others on a feature request made by someone else. So that's independent of our needs (although it might come up)

**Comment by vsoch** [comment] 2019-12-11 19:24
There isn't support for adding another tag to an existing image, but if you do upload the same ImageFile using the library client, it will share the same file:

https://github.com/singularityhub/sregistry/blob/master/shub/apps/library/views/images.py#L177

We can't easily add this to the snippets above (upload from browser or with sregistry) because the nginx upload won't give us a sha256 sum to ensure non-duplication. But hopefully over time more users will just use singularity to upload, and the other endpoints can be deprecated. Anyway, I'm closing the issue, because now uploading different tags for the same image file using the library client will not upload multiple images.

**Closed by vsoch** 2019-12-11 19:24 UTC
Labels: wontfix
