### ISSUE TITLE
scs library client (singularity 3.6.x) requires all lowercase to push

### ISSUE THREAD

**Issue by atharvnagarikar** [singularityhub/sregistry#331] opened 2020-12-21 06:13 UTC
Hi, I followed all your guidelines and setup GUI for the singularity registry server and I also verify the token and all but while trying to push the image to the collection I encountered the following fatal error 
![err5](https://user-images.githubusercontent.com/66713062/102745178-718f7000-4381-11eb-99de-344983c4290f.PNG)

Following image will show you the GUI along with the collection 
![err6](https://user-images.githubusercontent.com/66713062/102745312-adc2d080-4381-11eb-962b-269c6b145450.PNG)

Can you please help me with this

**Comment by vsoch** [comment] 2020-12-21 06:17
That looks correct - what version of Singularity are you using? sregistry is tested up to 3.5.x. The error message I see seems to be coming from Singularity so something is changed or erroneous there.

**Comment by atharvnagarikar** [comment] 2020-12-21 06:20
I'm using Singularity 3.6.4 version

**Comment by vsoch** [comment] 2020-12-21 06:21
Could you please try 3.5.2 or 3.5.1? That will rule out a version upgrade issue.

**Comment by vsoch** [comment] 2020-12-21 06:25
It looks like they've added a new check that checks against this regular expression: https://github.com/sylabs/scs-library-client/blob/31250b63795e4a20afd8f4f00b2ad3b34ec188e0/client/util.go#L28. So my thinking is that the issue is that you have a capital letter. Could you try an all lowercase name, no special characters, and if that works I can do an update to sregistry to enforce it as well?

**Comment by vsoch** [comment] 2020-12-21 06:27
Yeah, try changing your username to all lowercase, e.g., see how it matches after we do that:

```python
# Doesn't match regex and fails check as is now
re.search("^(library://)?([a-z0-9]+(?:[._-][a-z0-9]+)*/){2}([a-z0-9]+(?:[._-][a-z0-9]+)*)(:[a-z0-9]+(?:[,._-][a-z0-9]+)*)?$", "library://Singularity_CDAC_LSM/ai/test:latest")

# passes
re.search("^(library://)?([a-z0-9]+(?:[._-][a-z0-9]+)*/){2}([a-z0-9]+(?:[._-][a-z0-9]+)*)(:[a-z0-9]+(?:[,._-][a-z0-9]+)*)?$", "library://singularity_cdac_ssm/ai/test:latest")
<re.Match object; span=(0, 45), match='library://singularity_cdac_ssm/ai/test:latest'>
```

**Comment by atharvnagarikar** [comment] 2020-12-21 06:32
ok, I'll try and let you know

**Comment by vsoch** [comment] 2020-12-21 06:40
If the lowercase works, here is a PR for you to test that should create the same username, all lowercase. https://github.com/singularityhub/sregistry/pull/332 I have to be off to bed, looking forward to hearing how it goes!

**Comment by atharvnagarikar** [comment] 2020-12-22 04:15
lowercase work and now I can push the image to loaclhost

**Comment by vsoch** [comment] 2020-12-22 04:17
Great! Could you test the pull request and confirm that when you login with your username the username with capital letters  is already all lowercase? If we merge this pull request then the issue will be fixed for future users. Thanks for your help!

**Comment by atharvnagarikar** [comment] 2020-12-22 06:00
For pulling an image, should I use singularity registry client

**Comment by vsoch** [comment] 2020-12-22 06:05
No, you should use singularity with the library endpoint.

**Comment by atharvnagarikar** [comment] 2020-12-22 06:13
ok

**Comment by atharvnagarikar** [comment] 2020-12-22 07:15
I pulled the image successfully

**Comment by vsoch** [comment] 2020-12-22 07:15
Have you tested the PR?

**Comment by vsoch** [comment] 2020-12-22 18:49
@atharvnagarikar thank you for opening this issue - and I'm glad we have resolved it. You should consider in the future that open source is a two way street - I help you here, and when I create a solution for you, it is good practice to test it to confirm that it fixes your issue. If you want to have good relationships with maintainers, not just here but anywhere on GitHub, you should try to be more helpful.

**Closed by vsoch** 2020-12-22 18:49 UTC

**Comment by atharvnagarikar** [comment] 2020-12-28 03:45
@vsoch, thank you for your guidance and I was not able to come online due to some personal issues

**Comment by atharvnagarikar** [comment] 2020-12-28 03:46
Can you please elaborate #332
