### ISSUE TITLE
CI/CD  for singularity registry

### ISSUE THREAD

**Issue by ashwinidr3** [singularityhub/sregistry#311] opened 2020-07-02 08:03 UTC
hi again,

I am trying to create a CI/CD pipeline for singularity registry.
i am using Azure devops as SCM , and currently i am able to trigger the build in jenkins when a code is pushed (SCM polling)
i get the containers built successfully , now i need to push these containers to the registry that i have created on behalf of the user who pushed the changes.

i have figured out a way to get the access token of the user.
i create a .sregistry file on the fly with the details of the user , and try to push the container to the registry.
the push fails with 500 internal server error.

the push works fine when it is done from the same user account, but not from other account even though i populate all correct avlues in .sregitsry file.

i wanted to know, is this the best way and is it possible to resolve the issue or is there a simple way to do this?

Thanks in advance!!

**Comment by vsoch** [comment] 2020-07-02 08:13
The .sregistry file is deprecated in favor of the library API, I"d try that instead.

https://singularityhub.github.io/sregistry/docs/client#singularity-push

After that, if an error reproduces I'd look into what the error on the server is and go from there.

**Comment by ashwinidr3** [comment] 2020-07-02 08:19
to use singularity push the singularity registry needs to be configured with https , is that right? i am having trouble to set that up currently in my environment , so i was using sregistry-cli tool!

**Comment by vsoch** [comment] 2020-07-02 08:21
Yes that is correct. And I also know for a fact there is a link to the line you can change in the Singularity source code before compiling Singularity if you want to test with http :)

**Comment by ashwinidr3** [comment] 2020-07-02 08:25
yes, i have read that in your document!! but i suppose it wouldnt work when singularity is installed via RPM available via Redhat and not source code correct?

**Comment by vsoch** [comment] 2020-07-02 08:29
I suppose not! But it’s really best practice to have https, it’s enforced by Singularity and not Singularity registry here. That’s your best option, and if you have issue you can post an issue on the sylabs scs client board.

**Comment by ashwinidr3** [comment] 2020-07-02 08:46
ok, Thank you, i have tried to set up https in the past for singularity registry , but failed miserably!! so i started moving forward with this and thought to get back to https when i am done with atleast a minimal setup.

ideally speaking if am an user "A" and have .sregistry file with username and aceess token of user "B", i should be able to push the container to registry as user B correct?

**Comment by vsoch** [comment] 2020-07-02 12:41
If you have user B login and token you would be acting as user B, yes. I’d suggest looking at the error on the server to see if it’s something we can fix up.

**Comment by ashwinidr3** [comment] 2020-07-02 13:03
Thanks for your help!!

 sregistry push --name registry://test/lolcow:v2 lolcow_latest.sif
[client|registry] [database|sqlite:////glb/home/inadr3/.singularity/sregistry.db]

[1. Collection return status 500 Internal Server Error]

i could see only this much , when i run by giving the credentials of other user. (works fine for my userid and access token though)
is there any verbose flag for me to dig more? or do you know what this error is about?

**Comment by ashwinidr3** [comment] 2020-07-02 15:15
i cleared some cache files and gave it a try and it worked. runs smooth. thank you for the help  though :)

**Comment by vsoch** [comment] 2020-07-02 17:15
Sure! But if you deployed the registry, you should be able to see the actual server errors:

```
docker-compose logs uwsgi
docker-compose logs worker
```

etc.

Having the client say 500 internal server error isn't really super useful.

**Comment by vsoch** [comment] 2020-07-02 17:16
Closing issue since you have it fixed, good luck with your hacking!

**Closed by vsoch** 2020-07-02 17:16 UTC
