### ISSUE TITLE
ERROR: for sregistry_redis_1  Cannot start service redis: b'Unknown runtime specified containerd'

### ISSUE THREAD

**Issue by Smahane** [singularityhub/sregistry#140] opened 2018-08-31 17:40 UTC
Hello everyone,

I'm trying to setup sregistry internally following the [document ](https://singularityhub.github.io/sregistry/install) but i'm getting an error when trying to compose the images. Any idea what could be wrong? why the redis service is failing to start? Any debugging ideas are appreciate it too.

```
bash-4.4$ docker-compose up -d
Starting sregistry_db_1 ...
Starting sregistry_db_1
Starting sregistry_redis_1 ...
Starting sregistry_db_1 ... error

Starting sregistry_redis_1 ... error

ERROR: for sregistry_redis_1  Cannot start service redis: b'Unknown runtime specified containerd'

ERROR: for db  Cannot start service db: b'Unknown runtime specified containerd'

ERROR: for redis  Cannot start service redis: b'Unknown runtime specified containerd'
ERROR: Encountered errors while bringing up the project.
```
Also, I couldn't build the images locally. It complains about not being able to fetch some packages. I'm working behind a proxy. I'm assuming this is why.

Thank you,

**Comment by vsoch** [comment] 2018-08-31 17:59
This looks like an issue with your docker version, see here --> https://github.com/moby/moby/issues/24343 I'm still running an older version on my machine

```
docker --version
Docker version 18.06.0-ce, build 0ffa825
```
And I think there was a change in the runtime? Try some of the suggestions on the post and let me know if any of them work! And if so, if we can tweak the docker-compose recipe to ensure that it doesn't bug out for others too.

**Comment by Smahane** [comment] 2018-08-31 19:42
@vsoch  yes this solved the problem. thank you very much. Here is what i did :
```
sudo dnf -y install docker-ce-18.06.0.ce # this installs Docker version 18.06.0-ce, build 0ffa825
docker-compose down -v
sudo systemctl daemon-reload
sudo systemctl restart docker
docker-compose up -d

```
but now I can't get the registry (http://127.0.0.1) up and running!  I copied the "docker-compose.yml"  "nginx.conf" file to the local dir and restarted everything. everything seems to be fine but not sure what i'm missing! the page doesn't load.

```
bash-4.4$ docker-compose start
Starting db     ... done
Starting redis  ... done
Starting uwsgi  ... done
Starting nginx  ... done
Starting worker ... done
```
```
bash-4.4$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS                    NAMES
cfcd8e020a79        nginx               "nginx -g 'daemon of\u2026"   21 minutes ago      Restarting (1) 12 seconds ago                            sregistry_nginx_1
d550816996b6        vanessa/sregistry   "/bin/sh -c /code/ru\u2026"   21 minutes ago      Up 9 minutes                    3031/tcp                 sregistry_uwsgi_1
c135bed8f828        postgres            "docker-entrypoint.s\u2026"   21 minutes ago      Up 9 minutes                    5432/tcp                 sregistry_db_1
9dd7de0b49a2        redis:latest        "docker-entrypoint.s\u2026"   21 minutes ago      Up 9 minutes                    0.0.0.0:6379->6379/tcp   sregistry_redis_1
```

Don't see any errors in the logs :
```
docker-compose logs worker 
docker-compose logs nginx 
```

![image](https://user-images.githubusercontent.com/5471356/44931590-02f0f900-ad17-11e8-8008-981d38da4e3a.png)

**Comment by vsoch** [comment] 2018-08-31 21:01
heyo! Okay a few things I'm noticing:

1. The error message doesn't appear to be nginx? nginx error messages usually have a particular style (and that one looks different) unless you copied only part of it. Is there possibility that something else is running on that port (on your local machine?)

2. Since you had issues with the containers and changing docker versions, I would actually completely stop, remove, and remove the images (and pull again with the updated docker.) e.g.,

```
docker-compose stop
docker-compose rm
docker rmi vanessa/sregistry
docker rmi nginx
docker rmi postgres
docker rmi redis
```

3. You shouldn't need to copy any nginx configuration or docker compose - the defaults (at least without https) should do the trick. It could be that you are copying the nginx.conf from one of the "special" folders and thus the nginx server isn't working because it's not set up properly for it. So could you please confirm the docker-compose.yml and nginx.conf you are using, and why you needed to copy anything?

4. And I also noticed you didn't show that you removed completely the older containers (with the old docker, period) so before you bring up again,  I would build (note that nginx comes from the local folder, it's built) and then start them, given you just removed.

```
docker-compose build
```

and instead of running detached, run without the d so you can see complete error messages:

```
docker-compose up 
```
When it looks good, then control +C to kill the containers, and re-run with -d

```
docker-compose up -d 
```

**Comment by vsoch** [comment] 2018-08-31 21:02
And note that it's nginx that is restarting, telling us the issue is there. I would bet you that there is something else running on the host, or you started with a config that isn't loading, so the container has an error, the server doesn't start, and you see this message.

**Comment by vsoch** [comment] 2018-08-31 21:10
It also said "starting" and not "creating" which should have been the case for creating a new set of containers.

**Comment by vsoch** [comment] 2018-08-31 22:35
Yeah, so the https configuration requires that you have certificates set up and the server ready - you can't just change the config and have this out of the box working! Please use the ones that are there by default (for non https) and set up https when you have the server working.

I have no idea what APKINDEX is... I don't see any reference to it in the nginx folder so I think you are doing something strange again! Can you please give me the exact commands, and output, and files, for what you are doing? Also, in the case that it's trying to build something outside of nginx (which it shouldn't do) try just doing `docker-compose up` and seeing if it builds nginx. And **please** show me the commands you are doing and full output, I am severely limited when you just copy paste one cryptic error message.

**Comment by Smahane** [comment] 2018-08-31 23:30
Sorry about the luck of details. I assumed you know where you use APKINDEX that i couldn't find any reference to in the sregestry repo. Here is exactly what i did:
```
docker-compose stop
docker-compose rm
docker rmi vanessa/sregistry
docker rmi nginx
docker rmi postgres
docker rmi redis
sudo systemctl status docker
sudo systemctl daemon-reload
sudo systemctl restart docker
docker-compose build
```

The attacked is the output of the `docker-compose build` that includes the failure messages.
[output.txt](https://github.com/singularityhub/sregistry/files/2341875/output.txt)

**Comment by Smahane** [comment] 2018-08-31 23:33
Just to add, i did try to stop/start nginx manually on the host. It's running but that didn't help the containers to build.

**Comment by vsoch** [comment] 2018-08-31 23:37
Thank you! And oh goodness, this is a well known issue with the alpine image, look at this error issue board!

https://github.com/gliderlabs/docker-alpine/issues/279

Some thought it was mirrors, and then the last comment seems to be about the resolv.conf. So I think we should go through the issue board, and look for the :+1: (for when it worked for someone). When we get an image to build - I think what I want to do is build it locally and provide a vanessa/sregistry-nginx image that will capture these dependencies (meaning we don't need to build it).

It's dinner time and I'm closing up shot, but if you want to keep playing around try some of the suggestions on the board. I'll try to make some time over the holiday to see if I can get *something* built and then pushed to use as an image.

**Comment by vsoch** [comment] 2018-09-01 02:43
hey @Smahane some good news! I just built it on my machine without a hitch, and I pushed it to docker hub for you to try. So you will need to change the section of your docker compose. Instead of this:

```
nginx:
  restart: always
  build: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db
```

try this

```
nginx:
  restart: always
  image: vanessa/sregistry_nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db
```
I just brought up sregistry and it seems to work, at least over here!

![image](https://user-images.githubusercontent.com/814322/44941599-1c259400-ad6f-11e8-85dc-588eae2f4a0b.png)

If that works for you, then I'll adjust the docs / install routine to guide this to be the first option. You're the first one to hit this snag, so let's be sure it isn't something else first.

**Comment by vsoch** [comment] 2018-09-01 02:44
and [here is the container](https://hub.docker.com/r/vanessa/sregistry_nginx/) on Docker Hub.

**Comment by vsoch** [comment] 2018-09-04 17:34
hey @Smahane ! The point of giving the container for you on docker hub is that you don't need to build it, you can just change the docker-compose.yml as I showed you (instead of `build: nginx` it should be `image: vanessa/sregistry_nginx` and then do `docker-compose up` or `docker-compose up -d`

If you tell it to build, it's going to look for that as a folder, and that also suggests that you should double check your `docker-compose.yml` file because I bet you didn't change "build" to "image". Let me know if any of this isn't clear.

**Comment by Smahane** [comment] 2018-09-04 20:18
@vsoch  yes you're right. I had "build" instead of "image". thanks for pointing that out. 

Now `docker-compose up` hangs when it gets to uwsgi_1. I stopped docker-composer, restarted the daemon and docker with no luck!

Here is the output
[output 3.txt](https://github.com/singularityhub/sregistry/files/2350076/output.3.txt)

**Comment by Smahane** [comment] 2018-09-04 20:45
oh good to know. I was expecting something like "hehe, the server is up and running ! :)"
I'm getting an Operation timed out error! 

![image](https://user-images.githubusercontent.com/5471356/45056486-e111b200-b047-11e8-9e26-579a77a9fcfa.png)

I'm looking through the logs (`docker-compose logs --tail=30 -f` ) but don't see any obvious errors.
[log.txt](https://github.com/singularityhub/sregistry/files/2350169/log.txt)

**Comment by vsoch** [comment] 2018-09-04 20:52
That looks like you have another service that is controlling / doing something with the port on your localhost. Do you have a network administrator that can help you with this?

**Comment by vsoch** [comment] 2018-09-04 20:54
Is this running on a cloud / other place where I could log in and take a look? I don't know how I can help beyond that, I think you need someone to take a look that is familiar with your networking and host setup, and can debug.

**Comment by Smahane** [comment] 2018-09-04 23:14
@vsoch  this is a system in a lab behind a proxy. Unfortunately no networking experts are available to help. I'm on my own trying to use sregistry for my containers. I will keep googling i guess.

**Comment by vsoch** [comment] 2018-09-05 00:13
Ah! It’s likely the proxy. Can you share you settings folder files with me?

**Comment by Smahane** [comment] 2018-09-05 00:59
@vsoch which settings? docker's? share it via email?

**Comment by vsoch** [comment] 2018-09-05 01:04
There should be a folder (shub/settings) with a bunch of files (that you've configured based on the instructions correct?) If you have configured them according to the docs then zip them up and send to me (vsochat AT <my institution> DOT edu). If you haven't, then you probably need to read the docs --> https://singularityhub.github.io/sregistry//#deploy-a-registry-server 

It's after 9pm here and I haven't started dinner so please feel free to send to me tomorrow or later, lol.

**Comment by vsoch** [comment] 2019-10-07 21:53
No response for over a year, closing.

**Closed by vsoch** 2019-10-07 21:53 UTC
