### ISSUE TITLE
Can‘t update images in sregistry

### ISSUE THREAD

**Issue by qianglchina** [singularityhub/sregistry#294] opened 2020-04-01 02:20 UTC
When I push a image to sregistry updating some image, the image info  update in UI. Howerver if I pull  the updated images using singularity cli , I still got the old images.

singularity push -U app.sif library://sregistry/test/app
Change app.def and build a new one and push again, all works fine. In UI, the build Date upated.

singularity  pull  library://sregistry/test/app  
Still get the older one. There is no updating

**Comment by vsoch** [comment] 2020-04-01 02:24
Can you try the same thing but specify a tag (it could be that it’s pulling whatever is listed first without it) and if that reproduces the same issue please verify you are using the latest release on master (what is your version?) and please give me instructions to reproduce exactly? I can take a look later this week. Thanks!

**Comment by vsoch** [comment] 2020-04-01 02:29
Note that this issue looks like https://github.com/singularityhub/sregistry/issues/273

**Comment by qianglchina** [comment] 2020-04-03 10:24
Yeah, just like #273

**Comment by vsoch** [comment] 2020-05-23 19:10
This issue I believe is fixed, closing.

**Closed by vsoch** 2020-05-23 19:10 UTC
