### ISSUE TITLE
AGPL License Change

### ISSUE THREAD

**Issue by dctrud** [singularityhub/sregistry#67] opened 2017-12-16 03:11 UTC
I just noticed that the project changed to the AGPLv3 license. I'm just curious about the change - was it something required from Stanford?

Unfortunately this is going to mean I drop use of sregistry at UTSW or will have to use a fork from the last BSD licensed revision and develop/maintain that for our purposes. I had plans to incorporate a modified version of the shub app into our user portal, with that portal having a potential open source release in future. Given discussion on licensing that's been had, the derivative AGPL requirement isn't going to be compatible with our plans.

**Comment by vsoch** [comment] 2017-12-16 03:20
hey @dctrud ! Give me some time to chat with my colleague - the change was to prevent the project from leaving the open source world (and for example being modified privately by some company for profit) but I definitely didn't want that to extend to meaning that your group cannot use it (security / government seems to be a very different issue). It's actually very important to me that you can use it, so we will figure something out.

**Comment by vsoch** [comment] 2017-12-16 03:46
I am still waiting to chat with my colleague, but I think given your use case it would be ok to modify and use  - this to me says that if you modified and used publicly you would need to share, and use non publicly means that if someone (at your institution) requested the code, you would provide it. 

>> The GNU Affero General Public License is designed specifically to ensure that, in such cases, the modified source code becomes available to the community. It requires the operator of a network server to provide the source code of the modified version running there to the users of that server. Therefore, public use of a modified version, on a publicly accessible server, gives the public access to the source code of the modified version.

and then I'm looking at this site: http://www.affero.org/oagf.html

## Q: How does this license treat commercial enterprise use over intranets and internal networks?
A: Simply, if run internally to a commercial company, then the company isn't required to release source code back to the world. The license requires that if a user downloads the source they have the right to make improvements and not release these modifications. GNU GPL software in general addresses this issue the same way. If an employee has access to the source and has the right to make improvements, the commercial entity could probably view this work as work for hire and owned by the company and not have to be released outside.

I'll have more discussion later, but my current thoughts are 1) why can't we develop the software to integrate with a user portal so it's generally usable in that way, and 2) do you have suggestions for licenses that would ensure open source but not interfere with plans, and 3) what are your plans?

**Comment by vsoch** [comment] 2017-12-16 04:26
@akkornel can you help us brainstorm?

**Comment by akkornel** [comment] 2017-12-16 05:45
Hi @dctrud, good evening!  @vsoch asked me help help on this yesterday.  I'm not a lawyer, I'm a co-worker!  This wasn't a Stanford-initiated change (by "Stanford-initiated change", I mean that, as far as I'm aware, @vsoch wasn't asked/told to change the license by someone else).  @vsoch reached out to me yesterday (Thursday, I mean) for help.

My understanding is that @vsoch's goal is to prevent sregistry from being "locked up" commercially.  By that, I mean preventing an entity from taking sregistry code, using/improving it, and selling that, while keeping the code from being made available to (and also usable by) others.  I think you'll agree that the "viral" nature of the AGPL, and how the AGPL applies specifically to services (like web apps), certainly accomplishes that goal!

Also, I wanted to say, thanks for speaking up!  I'd like to be helpful to all sides here, so if you feel I'm being too confrontational, let me know!

This is an interesting conundrum:  As far as I'm aware—and I'm restricting myself to just OSI-Approved licenses—there's no license that recognizes a person's intentions (or their "plans for the future") versus what they're doing at this moment.  There's nothing that says "You can do this, as long as you're going to open-source it eventually.".  I think I can see how that takes a situation like yours and makes it problematic, because I don't think (from a licensing point of view) there is much difference between commercial (proprietary) software and software that isn't open-source now, but which might be some time in the future.

The problem is, I don't think the BSD types of licenses meet @vsoch's goal, because they are too permissive.  Sticking fast to the need for a BSD license would mean some sort of fork, or perhaps some sort of dual-license, but I think that could get complicated quickly!

I talked with @vsoch a bit (before she went offline for the night), and I'm wondering, would the MPL 2.0 work here?  The MPL-2.0 mixes well with other licenses (even the GPL), in that it limits itself only to the files that it's already been attached to, so the only way (that I believe) it would affect you is if you made changes to sregistry code files.  If you didn't, a notice and link (for example, to a GitHub commit or tag) should be enough.

I think the biggest place where the MPL-2.0 would affect you is if you were planning on making changes to sregistry code files, without contributing those changes back.

I don't know anything other than what you posted in this issue; were you planning on modifying sregistry code, instead of just using it?  Would it be possible to upstream (or post separately) those modifications, without posting anything related to other parts of the portal?

Thanks in advance for any info you can provide!

**Comment by vsoch** [comment] 2017-12-16 13:58
thanks @akkornel, this is so helpful! @dctrud, would MPL 2.0 (or another license) better fit your needs? @akkornel and I were reading here to learn about the different options (there are quite a few!) https://www.mozilla.org/en-US/MPL/2.0/FAQ/ Looking forward to hearing your thoughts.

**Comment by vsoch** [comment] 2017-12-16 14:11
https://christoph-conrads.name/why-i-chose-the-mozilla-public-license-2-0/

**Comment by dctrud** [comment] 2017-12-16 17:01
Hi @akkornel, @vsoch - I think the MPL 2.0 is quite a nice balance between preserving access to modifications to the core sregistry code while allowing it to be incorporated into larger works.

The HPC portal we have is a multi-app Django project, and since sregistry is a Django project it is feasible for me to use the sregistry shub Django app in our portal - with modifications so that fits in with the look and feel of our portal, and is integrated into existing functionality of the portal that e.g. allows launching of singularity containers from the web, provides secured reverse proxy setup for containerized web apps etc. The AGPL would be a no-go here, since if we want to release the portal open-source, we'd have to use AGPL for the derived work (our portal). I'm going to be pushing at work to get the portal available under an open-source license this year. The license used will not be mine to decide - but I don't think AGPL would be an option, given discussion I've had about licensing so far.

There is also talk about us providing some public web-based services, which has higher priority to the institution than the open-source release of the code. This would also stop me using AGPL sregistry code in our portal. There's definitely an argument that the AGPL is a good thing here, to stop people like us providing services first, and then maybe releasing code later / maybe not. Perhaps AGPL is actually what you want to avoid this situation?

Thinking selfishly, MPL 2.0 would be good for me, due to the source-file scope of the license. Contributing back enhancements/changes to the core is certainly what I'd want to do, as long as I am permitted by my institution. We could incorporate sregistry code, without being forced to license our original code in the derived work under any specific license.

I'm at an institution which doesn't have a great deal of experience releasing code openly. I've gone through the process before. Once I received permission to contribute to a project I'd started elsewhere, which was open sourced previously. The other time I requested an open-source license, but was given permission for binary only, non-profit academic use only (https://proteomics.swmed.edu/goat/). Most recently I was allowed to use BSD 3-clause for a very small project (https://github.com/dctrud/clair-singularity). This variability and uncertainty in licensing at our institutions makes flexible licenses attractive in projects I use - as they give me the most room to arrive at a way of open-sourcing our work.

**Comment by vsoch** [comment] 2017-12-16 17:58
Thanks for the details @dctrud - and I think we are migrating toward a good solution, and if you didn't see #69, I have things ready to go when we finalize! Let's do a few more checks / points of discussion:

>>  I'm going to be pushing at work to get the portal available under an open-source license this year. The license used will not be mine to decide - but I don't think AGPL would be an option, given discussion I've had about licensing so far.

It would be good to confirm with your group that AGPL wouldn't be an option for your (ultimate release). It's a more restricted license but perhaps if you discuss the pros and cons it wouldn't be such a bad choice for your portal.

>> There is also talk about us providing some public web-based services, which has higher priority to the institution than the open-source release of the code. 

Are these for profit services, or for your institution? This is the kind of thing I think should be avoided - we want to maintain code that is freely available and usable by anyone without needing to pay for services. I'm new to OSS, but that is the spirit I hold, we might call it academic open source, because the targeted user are those that don't have resources to pay and need to do honorable work.

>> Thinking selfishly, MPL 2.0 would be good for me, due to the source-file scope of the license. Contributing back enhancements/changes to the core is certainly what I'd want to do, as long as I am permitted by my institution. We could incorporate sregistry code, without being forced to license our original code in the derived work under any specific license.

I definitely agree this would be best for this particular use case!

If we do choose MPL 2.0, I'd like to write out a more human friendly contributing statement in the Contributors.md. Let me know your thoughts to all the above, and @akkornel please chime in when you can!

**Comment by dctrud** [comment] 2017-12-19 01:38
> It would be good to confirm with your group that AGPL wouldn't be an option for your (ultimate release). It's a more restricted license but perhaps if you discuss the pros and cons it wouldn't be such a bad choice for your portal.

It'd be nice, but I'm unlikely to be able to get an answer without a lot of time which I can't really put in now, when open source release is someway down the road. License choice involves departmental decisions, office of tech dev paperwork, and depends on where the funding has come from. It's also complicated by what else we have incorporated into the portal. Some of that does currently restrict options a bit, but might be replaced before we release.

To be honest I'm also personally somewhat against the AGPL for something like an HPC web portal, which is likely not going to be used wholesale by others (too customized to our site). There are a bunch of people out there in the HPC community with their own portals, who may only want to take pieces of our code etc. AGPL and even GPL can potentially hamper that somewhat.

> Are these for profit services, or for your institution?

No  - this would be hosting some stuff that would be freely accessible. We're a university interested in raising our profile in Bioinformatics, supporting publications through providing easy access to stuff via the web - that sort of thing.

As I said, being selfish MPL 2.0 is good for me!

**Comment by vsoch** [comment] 2018-04-18 17:30
hey @dctrud is this still an issue for you? If you aren't working at your old institution and it's no longer needed, it would be easiest to keep as is and I'll close the issue (and archive the PR).

**Comment by dctrud** [comment] 2018-04-18 17:52
Hi @vsoch - as you say this doesn't affect me any more as I am not at the institution using sregistry. Feel free to close.

**Comment by vsoch** [comment] 2018-04-18 17:53
Cool thanks @dctrud, closing. I think it was really useful to learn about the license types, and well worth the discussion!

**Closed by vsoch** 2018-04-18 17:53 UTC
