### ISSUE TITLE
nginx ldap_auth not found

### ISSUE THREAD

**Issue by groucho64738** [singularityhub/sregistry#225] opened 2019-08-22 14:54 UTC
Hi. I'm installing the sregistry with LDAP support and followed the directions, but I'm running into an issue where it seems like nginx can't find ldap_auth:

uwsgi_1      | [pid: 37|app: 0|req: 1/1] 10.251.16.20 () {38 vars in 592 bytes} [Thu Aug 22 09:52:40 2019] GET / => generated 8220 bytes in 690 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
uwsgi_1      | [pid: 38|app: 0|req: 1/2] 10.251.16.20 () {40 vars in 650 bytes} [Thu Aug 22 09:52:42 2019] GET /login/ => generated 5720 bytes in 660 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
uwsgi_1      | Not Found: /ldap_auth/login/
uwsgi_1      | [pid: 38|app: 0|req: 2/3] 10.251.16.20 () {40 vars in 759 bytes} [Thu Aug 22 09:52:44 2019] GET /ldap_auth/login/?next=http://myhost/login/ => generated 652 bytes in 26 msecs (HTTP/1.1 404) 3 headers in 116 bytes (1 switches on core 2)

I made sure in the Dockerfile and on the build line that I'm enabling the LDAP_AUTH plugin, and I see that django-ldap-auth and stuff is being added during the container builds.

Anyone have a hint on what to look for next? Thanks for your help.

**Comment by vsoch** [comment] 2019-08-22 14:58
Did you follow the instructions and uncomment ldap_auth from plugins installed? The second bullet here: https://singularityhub.github.io/sregistry/docs/plugins/ldap

https://github.com/singularityhub/sregistry/blob/master/shub/settings/config.py#L133

The message is telling us that django didn't find the urls associated with the login, so I'm guessing that is still commented.

**Comment by groucho64738** [comment] 2019-08-22 15:00
I have this in the shub/settings/config.py

PLUGINS_ENABLED = [
    'ldap_auth',
#    'google_build'
#    'pam_auth',
#    'globus',
#    'saml_auth'
]

**Comment by vsoch** [comment] 2019-08-22 15:00
Did you restart the containers after uncommenting?

**Comment by groucho64738** [comment] 2019-08-22 15:01
yes I did a docker-compose down and up again. Is there something inside of the uwsgi container itself when its restarted that I can look at to verify?

**Comment by vsoch** [comment] 2019-08-22 15:03
You would want to do docker-compose restart uwsgi worker - bringing up and down would just stop and bring up the same container, it works for some changes but not always.

**Comment by vsoch** [comment] 2019-08-22 15:03
You could do `python manage.py show_urls | grep ldap`

**Comment by vsoch** [comment] 2019-08-22 15:05
I'm building and bringing up the containers now to see if I can reproduce your issue. I also enabled the build-arg and uncommented the plugin.

**Comment by groucho64738** [comment] 2019-08-22 15:09
I logged into the vaness/sregistry container and ran the python command and saw this:
/ldap_auth/login/       django.contrib.auth.views.LoginView     ldap_auth-login

**Comment by vsoch** [comment] 2019-08-22 15:10
seems to be there then...

**Comment by groucho64738** [comment] 2019-08-22 15:10
the ngnix container there was not runnable python in.

**Comment by vsoch** [comment] 2019-08-22 15:10
Nginx is just the web server.

**Comment by groucho64738** [comment] 2019-08-22 15:11
Not sure if this matters, but after clicking on the ldap login button, I get the robot beep boop not found message, and the url at the top is http://mysite/ldap_auth/login/?next=http://mysite/login/

Is that formatted properly for what you'd expect?

**Comment by vsoch** [comment] 2019-08-22 15:13
ah here we go, it looks like it's hitting the wrong regex for a different url:

![image](https://user-images.githubusercontent.com/814322/63526736-dc027880-c4cd-11e9-8a8d-39f1cc21ef30.png)

**Comment by vsoch** [comment] 2019-08-22 15:13
Let me fizzle around a bit, give me a few minutes.

**Comment by groucho64738** [comment] 2019-08-22 15:13
sure thing. Thanks for being so responsive.

**Comment by vsoch** [comment] 2019-08-22 15:14
You're very welcome! :)

**Comment by vsoch** [comment] 2019-08-22 15:17
Tada! 

![image](https://user-images.githubusercontent.com/814322/63526960-42879680-c4ce-11e9-8eb4-502c03e4964d.png)

Sorry about that, it literally looks like when I did the last PR I removed the prefix for the user profile, so this bug would likely mess with a lot of callback urls (and I'm embarrassed to have missed it!) I'll get in a PR promptly for you to test - I don't have LDAP locally so I didn't go beyond that login screen.

**Comment by groucho64738** [comment] 2019-08-22 15:20
that's fine. I'm not sure my ldap config will work anyway, but one problem at a time.

**Comment by vsoch** [comment] 2019-08-22 15:20
That's been my experience too - LDAP is a bit hairy.

**Comment by groucho64738** [comment] 2019-08-22 15:21
just let me know how to get that version. I did a git clone of what was there this morning.

**Comment by vsoch** [comment] 2019-08-22 15:27
It will be a branch that I push (and open a PR for, so you would just pull the branch, or checkout in your repo that you have already and pull.

**Comment by vsoch** [comment] 2019-08-22 15:33
okay here is the branch! https://github.com/singularityhub/sregistry/pull/226 What we can do is have you  go through the basics (and get everything working) and I'll merge those fixes when everything looks good.

**Comment by groucho64738** [comment] 2019-08-22 15:46
I don't think I checked it out correctly.

**Comment by vsoch** [comment] 2019-08-22 15:49
You would need to do something like:

```bash
git checkout -b fix/ldap-url-order
git pull origin fix/ldap-url-order # and make sure origin refers to singularityhub/sregistry
docker-compose restart uwsgi
```
OR  you could bring down the containers for that repo (and leave on master branch, to update when it's merged)
```bash
$ docker-compose stop
```
And then go somewhere else to clone fresh, and since you already built, you can likely just bring up the containers and restart.

```bash
# git clone -b fix/ldap-url-order git@github.com:singularityhub/sregistry
cd sregistry
docker-compose up -d
docker-compose restart uwsgi worker # only if needed
```
What did you try?

**Comment by groucho64738** [comment] 2019-08-22 15:56
I had the branch name wrong, which'll do it. ugh, It'll be a few minutes to straighten some things out.

**Comment by vsoch** [comment] 2019-08-22 15:56
No worries, I'm literally at my computer all day until I get hungry and it's dinnertime :)

**Comment by groucho64738** [comment] 2019-08-22 15:59
Ok, I've got a login prompt and now ldap errors, but let me mess around from here. part of it could be the ldaps piece, so I'm going to tweak some things.

**Comment by vsoch** [comment] 2019-08-22 16:00
Good luck! The extent to which I can help from this point on is limited, but please keep me updated so we can merge the fixes when you are content.

**Comment by groucho64738** [comment] 2019-08-22 16:02
I logged in without secure ldap, so I think that's definitely progress. Thanks so much for your help.

**Comment by vsoch** [comment] 2019-08-22 16:08
Great! I'm going to go ahead and merge then, so other users don't run into this issue. Please open other issues if you run into them - I'm grateful for the additional testing because I just added a ton of security features to the registry, and tested the best that I could, but I'm just one dinosaur developer :)

**Closed** 2019-08-22 16:09 UTC
