### ISSUE TITLE
pushed container with tag "latest" does not update

### ISSUE THREAD

**Issue by RonaldEnsing** [singularityhub/sregistry#273] opened 2020-02-24 12:28 UTC
The status of a new container pushed to sregsitry is 'frozen', meaning that it cannot be overwritten. I would like to have new containers pushed to sregistry to have the status 'open' by default, so that I can overwrite containers without having to login the web interface to change the status manually, e.g. when I push containers from a CI. Is this option available? If so, how do I configure this?

edit: Maybe I should open a separate issue about this, but it also looks like the container does not get overwritten after setting status to 'open'. If I push another container (different content), the time stamp is modified but the container hash is not.

**Comment by vsoch** [comment] 2020-02-24 17:18
Hmm, I'm not sure where this is happening, because for the create command, frozen is set to False (see here) https://github.com/singularityhub/sregistry/blob/79ab935a2e51acfd7b22dca8d72382a8aabb318c/shub/apps/library/views/images.py#L226 and the default is also False https://github.com/singularityhub/sregistry/blob/master/shub/apps/main/models/containers.py#L79. Can you trace the operation you are doing - is it possibly the case you are hitting a container that already exists, or that there is a create somewhere we are overlooking?

**Comment by RonaldEnsing** [comment] 2020-03-04 11:53
Not sure what happened. It could be that the container existed before. I am not able to reproduce, even with a container that existed before. So I'll close this issue.

**Comment by RonaldEnsing** [comment] 2020-03-04 15:46
I was able to reproduce the issue after all. Although it turns our slightly different compared to what I stated before. The status is indeed 'Open' by default. However, when I push a container in order to overwrite an existing container, the time stamp in the web interface is modified, but the original container is not overwritten.

**Comment by vsoch** [comment] 2020-03-04 17:07
okay so just to clarify your situation:

 - you have a collection with a container that is not frozen
 - you push a new container with the same name _and_ tag (what is the tag?) and you expect the binary to be over-written
 - you see a timestamp update in the interface, but the container itself is the previous one (validated I assume with a pull and then checking some variable / version inside?)

**Comment by RonaldEnsing** [comment] 2020-03-04 18:36
> okay so just to clarify your situation:
> 
>     you have a collection with a container that is not frozen
> 
Yes
>     you push a new container with the same name _and_ tag (what is the tag?) and you expect the binary to be over-written

Yes. I simply used some custom tag ('latest').

>     you see a timestamp update in the interface, but the container itself is the previous one (validated I assume with a pull and then checking some variable / version inside?)
>

Yes. Although I did not use a `singularity pull`. I downloaded the container from the web interface. I don't expect that would make a difference though.
 
> 
> Where does frozen come in here?

Maybe I should have opened a new issue instead of re-opening this one after all. You are right that all of this happens with the 'open' status.

**Comment by vsoch** [comment] 2020-03-04 18:45
okay I'm going to update the title of the issue to better reflect what we are discussing.

**Comment by vsoch** [comment] 2020-03-04 18:46
One thing to test - could you try the exact same thing, but use a different tag (anything but latest?) I want to test if this is an issue with this "special" tag or a more global one.

**Comment by vsoch** [comment] 2020-03-04 18:49
Another thing to look at is if you shell into the interface and terminal, if you query for the container, do you see the image file defined at:

```bash
container.image
```
OR
```bash
container.metadata["image"]
```
If you look [here](https://github.com/singularityhub/sregistry/blob/master/shub/apps/library/views/images.py#L254) the bug could be that you've uploaded a container using two different methods, and it's returning one first, always. We should at least rule that out.

**Comment by vsoch** [comment] 2020-03-04 18:52
Then what I would try is shelling in, and using the request you do to pull (the full image URI) and manually walk through [this function](https://github.com/singularityhub/sregistry/blob/master/shub/apps/library/views/images.py#L307). You'd want to see what is returned when you call get_container based on the tags.

If that's not it, then the logic [here](https://github.com/singularityhub/sregistry/blob/master/shub/apps/library/views/images.py#L432) is likely the issue and you can put print statements there to see what is going on. Whenever I do this kind of debugging I make no assumptions - so it's a good idea to print out everything, and get an explicit trace of what is going on.

**Comment by RonaldEnsing** [comment] 2020-03-05 09:13
> One thing to test - could you try the exact same thing, but use a different tag (anything but latest?) I want to test if this is an issue with this "special" tag or a more global one.

I've tried with various tags and it's all the same.

> Another thing to look at is if you shell into the interface and terminal, if you query for the container, do you see the image file [...]

The output of `container.image` is `<ImageFile: ImageFile object (37)>`. The output of `container.metadata["image"]` is `KeyError: 'image'`. The `metadata` is empty, `container.metadata` returns `{}`.

> If you look here the bug could be that you've uploaded a container using two different methods, and it's returning one first, always. We should at least rule that out.

I am uploading using `singularity push ...` and downloading using the web interface.

**Comment by RonaldEnsing** [comment] 2020-03-05 10:04
Both the old and the new container are saved in `/var/www/images`. The old container is not removed, while it should. The database is only aware of the old container.

**Comment by vsoch** [comment] 2020-03-05 22:26
okay working on trying to reproduce your error now. I:

 - created a new instance of singularity registry server (secret, auth, etc.)
 - compiled a new singularity to allow for a non https remote
 - created a collection in the interface called "collection"
 - logged in to the remote with singularity login (instructions [here](https://singularityhub.github.io/sregistry/docs/client))
 - pulled `singularity pull docker://busybox:latest` and pushed with the singularity client.

```bash
$ singularity push -U busybox_latest.sif library://vsoch/collection/another:latest
WARNING: Skipping container verifying
 764.00 KiB / 764.00 KiB [======================================================================================] 100.00% 6.54 MiB/s 0s
```

I now have the busybox image in my local images folder mounted at /var/www/images in the container I believe.

```bash
$ ls images/collection/
another-sha256.78db97af609bdeb5205d0db00686cc5f7d136ea758588e22e15d11a078bdc7b8.sif
```
Now I pull another (different) busybox image, but I give it the same tag "another"

```bash
singularity pull docker://busybox:musl
singularity push -U busybox_musl.sif library://vsoch/collection/another:latest
```

I now have two images in my folder (and the old one isn't removed)

```
$ ls images/collection/
another-sha256.66853201baf2da684ce97e49845b9adaae5993fe3171d77a5ea39609c8c9cbc2.sif
another-sha256.78db97af609bdeb5205d0db00686cc5f7d136ea758588e22e15d11a078bdc7b8.sif
```
The first image is the shasum with 78*, the second (musl) has 66.
```
$ sha256sum busybox_latest.sif 
78db97af609bdeb5205d0db00686cc5f7d136ea758588e22e15d11a078bdc7b8  busybox_latest.sif
vanessa@vanessa-ThinkPad-T490s:/tmp$ sha256sum busybox_musl.sif 
66853201baf2da684ce97e49845b9adaae5993fe3171d77a5ea39609c8c9cbc2  busybox_musl.sif
```
So when I pull the container, I should get something with 66*.
```
$ singularity pull library://127.0.0.1/collection/another:latest
INFO:    Downloading library image
 764.00 KiB / 764.00 KiB [======================================================================================================================================] 100.00% 582.00 MiB/s 0s
WARNING: unable to verify container: another_latest.sif
WARNING: Skipping container verification
vanessa@vanessa-ThinkPad-T490s:/tmp$ sha256sum another_latest.sif 
78db97af609bdeb5205d0db00686cc5f7d136ea758588e22e15d11a078bdc7b8  another_latest.sif
```
Reproduced! We get the 78 image. Let me see if I can debug this, no time estimate for now, but definitely the new container isn't being replaced in the model as it properly should.

**Comment by vsoch** [comment] 2020-03-05 23:43
okay, so looks like we do a check if the user pushes the exact same image (although it's redundant)
```
        # If the final path exists, remove it
        if os.path.exists(final_container_path):
            os.remove(final_container_path)
```
That would at least remove a file that for some reason was re-pushed and is being saved again. We do indeed have two image file objects, and actually this might be the issue:

```
[x.name for x in ImageFile.objects.all()]                                                                                                                                       
Out[10]: 
['/var/www/images/collection/another-sha256.78db97af609bdeb5205d0db00686cc5f7d136ea758588e22e15d11a078bdc7b8-deksfl3p.sif',
 '/var/www/images/collection/another-sha256.66853201baf2da684ce97e49845b9adaae5993fe3171d77a5ea39609c8c9cbc2-hs5b8pls.sif']
```
Because when we check for an existing image file, we are looking for it based on the version (which might be different!) The problem is that we want just a name and tag here, but the filename also includes a version.

```
        # If there is a container file already existing, use it
        try:
            
            imagefile = ImageFile.objects.get(
                collection=container.collection.name, name=container_path
            )
        except ImageFile.DoesNotExist:
            imagefile = ImageFile.objects.create(
                collection=container.collection.name, name=container_path
            )
```
Ahh okay (it's actually about an hour passed since I started writing) but I found both issues:

 - for the container redundancy, it was a typo! In the section where we check for frozen, in the case that the container isn't frozen, instead of deleting the container and setting existing to be the selected, we needed to delete existing and set selected to be the new container.
 - for the delete of the old file, the signals (django signals) was set up but it wasn't triggering.

I should be able to open a PR soon, and I'll give you some specific points to test.

**Comment by vsoch** [comment] 2020-03-24 19:58
This was fixed, closing.

**Closed by vsoch** 2020-03-24 19:58 UTC
