### ISSUE TITLE
Support Singularity 3 library:// protocol

### ISSUE THREAD

**Issue by Flamefire** [singularityhub/sregistry#190] opened 2019-05-08 07:20 UTC
Singularity 3.x introduced the new library:// (used e.g. for https://cloud.sylabs.io/library) protocol which makes the whole sregistry client obsolete (from what I checked the singularity executable supports all operations the sregistry client supports, not 100% sure though)

Features:
- push
- pull
- search
- authentication (via token)

It would be great if this was supported by the server too possibly replacing (maybe via config) the shub:// protocol (which is the predecessor of library://)

**Comment by Flamefire** [comment] 2019-05-08 14:33
Helpful:
- responses are JSON with API endpoints defined in https://github.com/sylabs/singularity/blob/master/pkg/client/library/api.go, reads are GET, writes are POST as usual
- response types defined in https://github.com/sylabs/singularity/blob/master/pkg/client/library/response.go
- element types defined in https://github.com/sylabs/singularity/blob/master/pkg/client/library/models.go

With those it is pretty straigh-forward to create the endpoints.

**Comment by Flamefire** [comment] 2019-05-08 14:33
Helpful:
- responses are JSON with API endpoints defined in https://github.com/sylabs/singularity/blob/master/pkg/client/library/api.go, reads are GET, writes are POST as usual
- response types defined in https://github.com/sylabs/singularity/blob/master/pkg/client/library/response.go
- element types defined in https://github.com/sylabs/singularity/blob/master/pkg/client/library/models.go

With those it is pretty straigh-forward to create the endpoints.

**Comment by vsoch** [comment] 2019-05-08 14:51
So you are asking me to blindly reverse engineer the Sylabs library? Why don't you just use it?

**Comment by vsoch** [comment] 2019-05-08 14:52
So you are asking me to reverse engineer the Sylabs library, blindly. Why don't you just use it?

**Comment by vsoch** [comment] 2019-05-08 14:53
Something wonky is happening with GitHub issue comments - I keep posting and they are appearing above yours! :scream:

**Comment by vsoch** [comment] 2019-05-08 15:02
If this is important to you, I'd be happy to do this if you can provide a few example API requests/responses (with CURL or whatever your preference).  In other words, do the start of work to "use code as documentation" and assist with the development.

**Comment by vsoch** [comment] 2019-05-08 15:02
It looks like the issue is that your comment is dated "6 hours from now"

**Comment by vsoch** [comment] 2019-05-08 15:58
@Flamefire if you aren't sure about using it period for your resource (Docker) then I'd suggest holding off on this. Also I'll note that it's not intended to run on your resource, but alongside it.

**Comment by vsoch** [comment] 2019-05-08 17:14
See the conversation here (preserved since Slack doesn't let you read history). It looks like this functionality will be provided to you by Sylabs, so especially if you aren't sure about Docker, my recommendation is to wait for certainty about these two things. 

![image](https://user-images.githubusercontent.com/814322/57394327-34b63b80-7193-11e9-9975-977c3e8e78b6.png)

If anything changes, let me know.

**Comment by vsoch** [comment] 2019-06-11 16:27
hey @Flamefire  - I'm going to try to do this. First I'll start with pull, and we can add on to that. :)

**Comment by vsoch** [comment] 2019-06-11 17:54
hey @Flamefire I have a basic endpoint working for pull, and I have the first point for discussion. For image hashes, we would have a hash from the Singularity Registry client given a push, or for Google Cloud Build given an automated build or push, but for both of those, the hash is different from sha256.  See here - this is a third case when I allow the user to upload directly in the browser (no hash exists at all):

```bash
$ singularity --debug pull --library http://127.0.0.1 library://collection/busybox:latest
DEBUG   [U=1000,P=3883]    apiGet()                      apiGet calling http://127.0.0.1/v1/images//collection/busybox:latest
DEBUG   [U=1000,P=3883]    updateCacheSubdir()           Caching directory set to /home/vanessa/.singularity/cache/library
DEBUG   [U=1000,P=3883]    updateCacheSubdir()           Caching directory set to /home/vanessa/.singularity/cache/library
DEBUG   [U=1000,P=3883]    updateCacheSubdir()           Caching directory set to /home/vanessa/.singularity/cache/library
DEBUG   [U=1000,P=3883]    updateCacheSubdir()           Caching directory set to /home/vanessa/.singularity/cache/library
DEBUG   [U=1000,P=3883]    LibraryImageExists()          Cached File Sum(sha256.abcfa708ffa02a639413302ff753d047f6b00ebb3b0abc599e78b7d39ba684c4) and Expected Sum() does not match
INFO    [U=1000,P=3883]    pullRun()                     Downloading library image
DEBUG   [U=1000,P=3883]    DownloadImage()               Pulling from URL: http://127.0.0.1/v1/imagefile/collection/busybox:latest
DEBUG   [U=1000,P=3883]    DownloadImage()               OK response received, beginning body download
DEBUG   [U=1000,P=3883]    DownloadImage()               Created output file: /home/vanessa/.singularity/cache/library/busybox_latest.sif
 760.00 KiB / 760.00 KiB [============================================================================================] 100.00% 58.46 MiB/s 0s
DEBUG   [U=1000,P=3883]    DownloadImage()               Download complete
FATAL   [U=1000,P=3883]    pullRun()                     Cached File Hash(sha256.abcfa708ffa02a639413302ff753d047f6b00ebb3b0abc599e78b7d39ba684c4) and Expected Hash() does not match
```

For the first (client push) I *could* update the client (and it would be reasonable to do) but for the second, I can't control how gcloud provides the version - I'd have to have a custom build step that calculates it and then sends as part of the response back to the registry (also doable.) . I'm guessing the library push command (as part of it) calculates the hash to save, so I could implement that. The best case solution here would be to:

 - change the hash algorithm for sregistry push to shasum256
 - try a custom build step for Google Build
 - rely on singularity push to generate the correct hash.

Thoughts? I don't see a solution for an image uploaded in the browser, but I'm thinking this isn't a common use case.

**Comment by Flamefire** [comment] 2019-06-12 07:04
> we would have a hash from the Singularity Registry client given a push, or for Google Cloud Build given an automated build or push, but for both of those, the hash is different from sha256. 

I don't understand. The `singularity` binary is the authoritative source for the one valid hash. So the algorithm to generate that hash is known. The registry needs to be able to handle that. I've forgotten the details but IIRC `singularity` queries by a hash first (or asks for the hash?) to check whether to upload/download the image. So the registry must store (and/or generate) **that** hash for the stored images.

>  I can't control how gcloud provides the version

Can you elaborate on this? How/When/What does gcloud have to do with this and what does it provide?

> - change the hash algorithm for sregistry push to shasum256
> - try a custom build step for Google Build
> - rely on singularity push to generate the correct hash

The server (sregistry) needs to have the correct hash (as per `singularity push/pull`). So why not generate it on the server? This solves all problems, doesn't it? You can't rely on the client sending you a hash for an image it uploaded. Ever. It might be altered (accidentally or on purpose)

**Comment by vsoch** [comment] 2019-06-12 12:12
Hey @Flamefire ! I can provide some more detail to answer your questions!

> So the registry must store (and/or generate) that hash for the stored images.

For local files (meaning those that are pushed directly), generally I think it would be a burden on the server to need to calculate these hashes on every push. That said, it could be run as a quick task if you think this is better than calculating it on the host.

> Can you elaborate on this? How/When/What does gcloud have to do with this and what does it provide?

Oh of course! So I've been working hard in the last week or so to add a plugin for Google Cloud Build + GitHub, meaning that you commit recipes to GitHub, the registry receives the webhook, and a [Google Cloud Build](https://cloud.google.com/cloud-build/docs/) is triggered. With cloud build, we can provide one of the singularityware/singularity docker containers as base, giving the registry owned much nicer control over that. It uses these things called [build steps](https://cloud.google.com/cloud-build/docs/build-config#build_steps) to clone the repo (git builder), build the container (singularityware container), and then post back to the registry (and the registry queries for final data like the static files location). Currently, their API calculates a hash for us, but the one that comes back (associated with the blob in Storage) is [CRC32c](https://cloud.google.com/storage/docs/gsutil/commands/hash). So what I'm suggesting here is to add another build step between finishing the container and sending the signal back to the registry to calculate a sha256 sum, probably write it to a file in the build directory, and then have that content be sent back in the post to the server.

> The server (sregistry) needs to have the correct hash (as per singularity push/pull). So why not generate it on the server? 

So yes - we could do this as a task for any containers that sit with the server. For Google Build, they remain in Google Storage so we would need this extra build step. For containers uploaded via the file interface, it would again need to be done on the server.

This plugin is not quite ready to share with the community, but it's running on a server so if you'd like to take a look to test it out, I'd be happy to send you (off of GitHub) a URL and then the PR in progress to look at the code.

**Comment by Flamefire** [comment] 2019-06-12 13:12
> For local files (meaning those that are pushed directly), generally I think it would be a burden on the server to need to calculate these hashes on every push. That said, it could be run as a quick task if you think this is better than calculating it on the host.

Well having done some web development  some time ago I strongly believe in "never trust the client". So IMO it should always be done by the server or at least under the servers control. Unfortunately the singularity client expects `sha256.*` hashes, so that is what the server must use. If the server can instruct the Gcloud build to generate such a hash, fine. So if that is trustworthy / save against manipulation use it.

**Comment by vsoch** [comment] 2019-06-12 13:15
Alrighty, I'll add this to the todo list. I completely agree.

**Comment by vsoch** [comment] 2019-06-12 14:54
Ok, I added the sha256 calculation to the server, and we have pull!

```bash
$ singularity --debug pull  --library http://127.0.0.1 collection/busybox:latest
DEBUG   [U=1000,P=15623]   apiGet()                      apiGet calling http://127.0.0.1/v1/images//collection/busybox:latest
DEBUG   [U=1000,P=15623]   updateCacheSubdir()           Caching directory set to /home/vanessa/.singularity/cache/library/sha256.abcfa708ffa02a639413302ff753d047f6b00ebb3b0abc599e78b7d39ba684c4
DEBUG   [U=1000,P=15623]   updateCacheSubdir()           Caching directory set to /home/vanessa/.singularity/cache/library
DEBUG   [U=1000,P=15623]   updateCacheSubdir()           Caching directory set to /home/vanessa/.singularity/cache/library/sha256.abcfa708ffa02a639413302ff753d047f6b00ebb3b0abc599e78b7d39ba684c4
DEBUG   [U=1000,P=15623]   updateCacheSubdir()           Caching directory set to /home/vanessa/.singularity/cache/library
WARNING [U=1000,P=15623]   pullRun()                     unable to verify container: error while searching for signature blocks: no signatures found for system partition
This image is not signed, and thus its contents cannot be verified.
Do you with to proceed? [N/y] y
```
I'm not sure about the signature business, but the container is pulled! So that's a start :) For Google Build it will be a bit more complicated to add a build step to calculate the sha256 sum, will work on that soon but probably not update the instance (people are testing it now).

**Comment by vsoch** [comment] 2019-06-27 22:01
hey @Flamefire if you want to test the pull, details are here https://twitter.com/vsoch/status/1144361770661928962. Note that Singularity 3.1 will work, but 3.2.1 they broke passing of the --library variable, so it won't. See https://github.com/sylabs/singularity/issues/3815

**Comment by Flamefire** [comment] 2019-06-28 07:47
I tried the pull endpoint and it does work. Tested with 3.2.1

**Comment by vsoch** [comment] 2019-06-28 09:22
Yeah see the issue, works with 3.1 only.

**Comment by Flamefire** [comment] 2019-06-28 09:26
> Yeah see the issue, works with 3.1 only.

Excuse me, what do you mean? I wrote that I tested it with 3.2.1 and it did work.

**Comment by vsoch** [comment] 2019-06-28 12:07
See https://github.com/sylabs/singularity/issues/3815#issuecomment-506710499

**Comment by vsoch** [comment] 2019-11-07 16:26
The basic endpoints first listed here are supported, closing issue.

**Closed by vsoch** 2019-11-07 16:26 UTC
